version: 1.0.{build}
configuration: Release
before_build:
  - cmd: cd src 
  - cmd: nuget restore
build:
  project: src/SequencedAggregate.sln
  verbosity: minimal
test:
  assemblies:
  - 'SequencedAggregate.Tests.Unit.dll'
services:
  - mssql2014